#name: mailserver
#categories: network
#description: self host mail server with smtp relay and web client
#platform: linux
#logo: https://github.com/docker-mailserver/docker-mailserver/blob/master/docs/content/assets/logo/.src/dmo-logo.png?raw=true
#note: 

services:

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    hostname: ${MAIL_HOSTNAME}
    env_file: mailserver.env
    environment:
      - POSTFIX_MAILBOX_SIZE_LIMIT=${MAILBOX_SIZE_LIMIT}
      - POSTFIX_MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - DEFAULT_RELAY_HOST=${DEFAULT_RELAY_HOST}
      - RELAY_USER=${RELAY_USER}
      - RELAY_PASSWORD=${RELAY_PASSWORD}
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ${PATH_MAILSERVER}/mail-data/:/var/mail/
      - ${PATH_MAILSERVER}/mail-state/:/var/mail-state/
      - ${PATH_MAILSERVER}/mail-logs/:/var/log/mail/
      - ${PATH_MAILSERVER}/config/:/tmp/docker-mailserver/
      - ${PATH_NPM_LETSENCRYPT}:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  # commend out if you don't need mail webui
  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: ${COMPOSE_PROJECT_NAME}-roundcube
    restart: unless-stopped
    volumes:
      - ${PATH_ROUNDCUBE}/www:/var/www/html
      - ${PATH_ROUNDCUBE}/sqlite:/var/roundcube/db
    command: sh -c "chown -R root:root /var/roundcube/db"
    ports:
      - ${ROUNDCUBE_PORT}:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://${MAIL_HOSTNAME}
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://${MAIL_HOSTNAME}
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=${MESSAGE_SIZE_LIMIT}
      # - ROUNDCUBEMAIL_USERNAME_DOMAIN= # auto add domain to username
