#name: owncast
#categories: stream
#description: watch rtmp streams
#platform: linux
#logo: https://owncast.online/images/owncast-logo-1000x1000.png
#note: 

services:
  owncast:
    image: owncast/owncast:latest
    container_name: ${COMPOSE_PROJECT_NAME}-owncast
    ports: 
      - ${HOST_PORT_WEB}:8080
      - ${HOST_PORT_RTMP}:1935
    restart: unless-stopped
    # network_mode: bridge # we don't need a separate network created, just join default bridge
    volumes:
      - ${PATH_HOST_DATA}:/app/data
