#name: cloudflare-ddns
#categories: network
#description: If you have dynamic IP and registered domain with cloudflare, this will update it
#platform: linux
#logo: https://developers.cloudflare.com/_astro/logo.BU9hiExz.svg

services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - ZONE=${ZONE}
      - SUBDOMAIN=${SUBDOMAIN}
      - PROXIED=${PROXIED}
      