services:
  passmark:
    image: yvvidolov/linux-benchmark-cli
    container_name: ${COMPOSE_PROJECT_NAME}
    command: >
      bash -ce "cat /etc/motd; 
               echo '';
               echo '$ ./help # to get usage information';
               tail -f /dev/null"
    # volumes: # This is needed to benchmark storage devices
      # - /host_path_from_hdd:/home/dev/hdd
      # - /host_path_from_nvme:/home/dev/mmc
      # - /host_path_from_ssd:/home/dev/ssd
